services:
  couchdb:
    expose:
      - 5984
    image: treehouses/rpi-couchdb:2.1.1
    ports:
      - "2200:5984"
      - "2201:5986"
  db-init:
    image: treehouses/planet:rpi-db-init-latest
    depends_on:
      - couchdb
    environment:
      - COUCHDB_HOST=http://couchdb:5984
  planet:
    image: treehouses/planet-dev:rpi-latest
    ports:
      - "3000:3000"
    volumes:
      - "../:/planet"
    depends_on:
      - couchdb
version: "2"
